engines:
  eslint:
    enabled: false
    channel: "eslint-3"
    config:
      config: .eslintrc.json
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 112
ratings:
  paths:
  - client/app/**
  - server/**
  - "**.js"
exclude_paths:
- "**.spec.js"
- "**.e2e.js"
- tests/**/*
- node_modules/**
- gulp/**
- reports/**
