engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.json
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
ratings:
  paths:
  - client/app/**
  - server/**
  - "**.js"
exclude_paths:
- tests/**/*
- node_modules/**
- gulp/**
- bower_components/**
- reports/**
