fail_on_violations: true
ruby:
  enabled: false
jshint:
  enabled: false
coffeescript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc.json
scss:
  enabled: true
  config_file: .sass-lint.yml
