compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmAuditExcludePackages:
  - angular
  - bootstrap
  - bootstrap-sass
  - lodash.pick

yarnPath: .yarn/releases/yarn-4.9.1.cjs
